# Generated by Django 5.1.4 on 2026-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service_display_order_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/covers/'),
        ),
    ]
