# Generated by Django 5.1.4 on 2026-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='read_time_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
