# Generated by Django 5.1.4 on 2026-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_insight_read_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_designation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
