# Generated by Django 5.1.4 on 2026-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testimonial_client_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='svg_icon',
            field=models.TextField(default='asdsa'),
            preserve_default=False,
        ),
    ]
