# Generated by Django 5.1.4 on 2026-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_industry_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20),
        ),
    ]
