# Generated by Django 5.1.4 on 2026-03-16 05:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_jobopening_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
