# Generated by Django 5.1.4 on 2026-03-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_jobopening_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='short_description',
            field=models.CharField(default='test content ', max_length=500),
            preserve_default=False,
        ),
    ]
