# Generated by Django 5.1.4 on 2026-03-23 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_privacypolicy_termsofservice_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudyTechnology',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.casestudy')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='technologies',
            field=models.ManyToManyField(through='website.CaseStudyTechnology', to='website.technology'),
        ),
    ]
