# Generated by Django 5.1.4 on 2026-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_technology_casestudytechnology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='challenge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
