# Generated by Django 5.1.4 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_casestudy_challenge_casestudy_goal_casestudy_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
