# Generated by Django 5.1.4 on 2026-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_user_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallSchedule',
        ),
        migrations.AddField(
            model_name='booking',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
