# Generated by Django 5.1.4 on 2026-03-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_callschedule_booking_google_meet_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='google_meet_link',
            new_name='meet_link',
        ),
    ]
