# Generated by Django 5.1.4 on 2026-04-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_booking_client_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='svg_mockup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
