# Generated by Django 5.1.4 on 2026-04-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_service_svg_icon_service_svg_mockup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='svg_icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='svg_mockup',
        ),
        migrations.AlterField(
            model_name='industry',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='services/covers/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='services/icons/'),
        ),
    ]
