# Generated by Django 5.1.4 on 2026-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_service_svg_icon_remove_service_svg_mockup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='case_studies/'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='svg_icon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='platform_image',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/platform/'),
        ),
    ]
