# Generated by Django 5.1.4 on 2026-04-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_casestudy_product_image_alter_industry_svg_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/'),
        ),
    ]
