# Generated by Django 5.1.4 on 2026-04-13 06:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_casestudy_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='about',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
