# Generated by Django 5.1.4 on 2026-04-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_casestudy_about_remove_casestudy_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=models.TextField(),
        ),
    ]
