# Generated by Django 5.1.4 on 2026-04-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_casestudy_about_casestudy_challenge_casestudy_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='product_image',
        ),
    ]
