# Generated by Django 5.1.4 on 2026-04-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_casestudy_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_requested',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
