# Generated by Django 5.1.4 on 2026-04-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_remove_booking_service_requested_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_client_booking',
        ),
    ]
