# Generated by Django 5.1.4 on 2026-04-16 07:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_booking_unique_client_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='about',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='CaseStudyImage',
        ),
    ]
