# Generated by Django 5.1.4 on 2026-04-16 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_remove_casestudy_about_remove_casestudy_challenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='case_studies/images/')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.casestudy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
