# Generated by Django 5.1.4 on 2026-04-16 07:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_casestudyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=models.TextField(),
        ),
    ]
