# Generated by Django 5.1.4 on 2026-04-17 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_service_index_remove_service_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='services/icons/')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service_index',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='services/covers/'),
        ),
    ]
