# Generated by Django 5.1.4 on 2026-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_service_page_service_index_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
