# Generated by Django 5.1.4 on 2026-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_contactus_phone_alter_jobopening_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='phone',
        ),
        migrations.AddField(
            model_name='companycontact',
            name='address_australia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='address_india',
            field=models.TextField(blank=True),
        ),
    ]
