# Generated by Django 5.1.4 on 2026-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_remove_companycontact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='address_australia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='address_india',
            field=models.TextField(),
        ),
    ]
