# Generated by Django 5.1.4 on 2026-05-05 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_companycontact_address_australia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCallFAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
