# Generated by Django 5.1.4 on 2026-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_schedulecallfaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='schedulecallfaq',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='faq',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulecallfaq',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
