# Generated by Django 5.1.4 on 2026-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_faq_options_alter_schedulecallfaq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
