# Generated by Django 5.1.4 on 2026-05-22 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_casestudy_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/hero/')),
                ('hero_button_text', models.CharField(default='Book a Strategy Call', max_length=100)),
                ('hero_button_url', models.CharField(default='schedule-call', max_length=255)),
                ('problems_title', models.CharField(default='Where things break down', max_length=255)),
                ('problems_description', models.TextField(blank=True)),
                ('problems_list_title', models.CharField(default='Common challenges we see:', max_length=255)),
                ('solution_title', models.CharField(default='How we solve this', max_length=255)),
                ('solution_description', models.TextField(blank=True)),
                ('solution_list_title', models.CharField(default='What we typically implement:', max_length=255)),
                ('capabilities_title', models.CharField(default='Key capabilities', max_length=255)),
                ('capabilities_image', models.ImageField(blank=True, null=True, upload_to='services/capabilities/')),
                ('why_choose_title', models.CharField(default='Why choose us', max_length=255)),
                ('why_choose_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Let’s build something great together', max_length=255)),
                ('cta_subtitle', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(default='Book a Strategy Call', max_length=100)),
                ('cta_button_url', models.CharField(default='contact', max_length=255)),
                ('service_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.service_page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCapabilityItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_items', to='website.servicedetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProblemCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='services/problems/')),
                ('display_order', models.IntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_cards', to='website.servicedetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProblemItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list_items', to='website.servicedetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSolutionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_items', to='website.servicedetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWhyChooseItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='SVG or icon class', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='website.servicedetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
