# Generated by Django 5.1.4 on 2026-05-22 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_servicedetail_servicecapabilityitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='industries/hero/')),
                ('challenges_title', models.CharField(default='Operational Challenges', max_length=255)),
                ('challenges_description', models.TextField(blank=True)),
                ('challenges_image', models.ImageField(blank=True, null=True, upload_to='industries/challenges/')),
                ('impact_title', models.CharField(default='Operational Impact', max_length=255)),
                ('solutions_title', models.CharField(default='Solutions Built Around Real Workflows', max_length=255)),
                ('solutions_description', models.TextField(blank=True)),
                ('provide_title', models.CharField(default='What We Provide', max_length=255)),
                ('provide_description', models.TextField(blank=True)),
                ('why_choose_title', models.CharField(default='Why Choose Us', max_length=255)),
                ('why_choose_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(blank=True, max_length=255)),
                ('cta_subtitle', models.TextField(blank=True)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryImpactItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('industry_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_items', to='website.industrydetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='IndustryProvideItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('industry_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provide_items', to='website.industrydetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='IndustrySolutionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('industry_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_items', to='website.industrydetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='IndustryWhyChooseItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('industry_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='website.industrydetail')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
