# Generated by Django 5.1.4 on 2026-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_industrydetail_industryimpactitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydetail',
            name='challenges_badge_text',
            field=models.CharField(default='Challenges', max_length=100),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='challenges_image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='cta_image',
            field=models.ImageField(blank=True, null=True, upload_to='industries/cta/'),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='impact_badge_text',
            field=models.CharField(default='Impact', max_length=100),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='provide_badge_text',
            field=models.CharField(default='What We Provide', max_length=100),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='solutions_badge_text',
            field=models.CharField(default='Solutions', max_length=100),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='why_choose_badge_text',
            field=models.CharField(default='Why choose us', max_length=100),
        ),
    ]
