# Generated by Django 5.1.4 on 2026-05-22 13:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_industrydetail_challenges_badge_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydetail',
            name='challenges_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='cta_subtitle',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='hero_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='provide_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='solutions_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='why_choose_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industryimpactitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industryprovideitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrysolutionitem',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
