# Generated by Django 5.1.4 on 2026-05-25 05:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_industrydetail_challenges_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrydetail',
            name='cta_image',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='cta_button_text',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='cta_button_url',
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='hero_title',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
