# Generated by Django 5.1.4 on 2026-05-25 05:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_remove_industrydetail_cta_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='hero_button_url',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='hero_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='hero_title',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='problems_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='solution_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='why_choose_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
