# Generated by Django 5.1.4 on 2026-05-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_remove_servicedetail_hero_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='service_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.service_index'),
        ),
    ]
