# Generated by Django 5.1.4 on 2026-05-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_alter_servicedetail_service_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='service_main_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.service_page'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.service_index'),
        ),
    ]
