# Generated by Django 5.1.4 on 2026-05-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_servicedetail_service_main_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydetail',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.industry'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.service_page'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.service_index'),
        ),
    ]
