# Generated by Django 5.1.4 on 2026-05-26 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_alter_industrydetail_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='problems_title',
            field=ckeditor.fields.RichTextField(blank=True, default='Where things break down'),
        ),
    ]
