# Generated by Django 5.1.4 on 2026-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_alter_servicedetail_problems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='problems_title',
            field=models.TextField(default='Where things break down', max_length=255),
        ),
    ]
