# Generated by Django 5.1.4 on 2026-06-01 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_alter_servicedetail_problems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydetail',
            name='challenges_image_caption',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255),
        ),
    ]
