# Generated by Django 5.1.4 on 2026-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_alter_industrydetail_challenges_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydetail',
            name='challenges_image_caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
