# Generated by Django 5.1.4 on 2026-06-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_industrydetail_challenges_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='show_on_other_projects',
            field=models.BooleanField(default=True),
        ),
    ]
