# Generated by Django 5.1.4 on 2026-06-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_casestudy_show_on_other_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
