# Generated by Django 5.1.4 on 2026-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_casestudy_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='index_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
