# Generated by Django 5.1.4 on 2026-08-10 04:51

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_casestudy_index_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('published_at', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('display_on_website', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='website.teammember')),
            ],
            options={
                'ordering': ['display_order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/content/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('display_on_website', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.blog')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
