# Generated by Django 5.1.4 on 2026-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_blog_blogdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.FileField(upload_to='team/'),
        ),
    ]
