# Generated by Codex on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0061_alter_teammember_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("development", "Development"),
                    ("ai", "AI"),
                    ("cloud", "Cloud"),
                    ("cybersecurity", "Cybersecurity"),
                    ("data_science", "Data Science"),
                    ("business", "Business"),
                    ("sales", "Sales"),
                    ("marketing", "Marketing"),
                    ("seo", "SEO"),
                    ("healthcare", "Healthcare"),
                    ("finance", "Finance"),
                    ("e_commerce", "E-commerce"),
                    ("ui_ux_design", "UI/UX Design"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
