# Generated by Django 5.1.4 on 2026-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time_minutes',
            field=models.PositiveIntegerField(default=1, help_text='Auto-calculated from blog content at 238 WPM. Do not edit manually.'),
        ),
    ]
