# Generated by Django 5.1.4 on 2026-08-14 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_alter_blog_read_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Enter descriptive ALT text for the blog image.', max_length=125),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Meta description. Recommended maximum: 156 characters.', max_length=156),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='SEO title tag. Recommended maximum: 60 characters.', max_length=60),
        ),
    ]
