# Generated by Django 5.1.4 on 2026-08-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_blogfaq_blog_image_alt_text_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfaq',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global FAQ that appears on every blog post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.blog'),
        ),
    ]
