# Generated by Django 5.1.4 on 2026-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_blogfaq_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmissionGuard',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
