# Generated by Django 5.1.4 on 2026-09-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_technologycategory_technology_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologycategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='technologycategory',
            name='slug',
        ),
    ]
