# Generated by Django 5.1.4 on 2026-09-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_all_technology_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologycategory',
            name='all_technology_category',
        ),
        migrations.DeleteModel(
            name='all_technology_category',
        ),
    ]
