"""
Django settings for codigo project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os, sys
from pathlib import Path
from django.contrib.messages import constants as messages

from dotenv import load_dotenv
import os
from decouple import config

load_dotenv()  # loads variables from .env

# --- Google Meet (Calendar API) — optional; see website/google_meet.py ---
# Booking flow uses Zoom by default. Uncomment import + fallback in website/views.py
# to use Meet when Zoom fails. Share the calendar with the service account email.
GOOGLE_SERVICE_ACCOUNT_FILE = os.environ.get("GOOGLE_SERVICE_ACCOUNT_FILE")
GOOGLE_CALENDAR_ID = os.environ.get("GOOGLE_CALENDAR_ID", "primary")

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR=os.path.join(BASE_DIR,'template')
STATIC_DIR=os.path.join(BASE_DIR,'static')

BASE_DIRR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIRR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '%a4-))8=7y0*z=de#zg+4vft8q9p9q27!gx9vteo6jmr#)k7y7'
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'django_recaptcha',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'website',
    'corsheaders',
    'ckeditor',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

JAZZMIN_SETTINGS = {

    "site_title": "Codigomantra Admin",
    "site_header": "Codigomantra Administration",
    "site_brand": " ",

    "site_logo": "images/codigo-mantra-logo.svg",

    "login_logo": "images/codigo-mantra-logo.svg",

    "site_logo_classes": "img-circle",
    "site_icon": "images/favicon.png",

    "welcome_sign": "Welcome to Codigomantra Admin",
    "copyright": "Codigomantra",
    "user_avatar": None,

    "topmenu_links": [

        {"name": "Dashboard", "url": "admin:index"},

        {"name": "Website", "url": "/", "new_window": True},

    ],

    "usermenu_links": [
        {"name": "Visit Website", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,

    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": [
        "auth",
        "website.services",
        "website.industries",
        "website.testimonials",
        "website.teammember",
        "website.casestudy",
        "website.faq",
        "website.newsletter",
        "website.jobopening",
        "website.application",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "website.service": "fas fa-briefcase",
        "website.industry": "fas fa-industry",
        "website.product": "fas fa-box",
        "website.testimonial": "fas fa-comment",
        "website.teammember": "fas fa-user-tie",
        "website.casestudy": "fas fa-chart-line",
        "website.faq": "fas fa-question-circle",
        "website.newsletter": "fas fa-envelope",
        "website.jobopening": "fas fa-briefcase",
        "website.application": "fas fa-file-alt",
        "website.photoarchive": "fas fa-images",
    },

    "default_icon_parents": "fas fa-angle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": False,

    "custom_css": None,
    "custom_js": None,

    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },

}


ROOT_URLCONF = 'codigo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processor.navbar_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'codigo.wsgi.application'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Or other authentication class
    ],
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,                  
    'BLACKLIST_AFTER_ROTATION': True,               
    'UPDATE_LAST_LOGIN': True,                      
}


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_USER_MODEL = 'users.User'
CORS_ALLOW_ALL_ORIGINS = True

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS=[
# STATIC_DIR,
# ]


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS=[
STATIC_DIR,
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.org'
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'er.rkkansal@gmail.com'
#EMAIL_HOST_PASSWORD = ''
#EMAIL_USE_TLS = True



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = "Codigo Mantra <abbas.codigo@gmail.com>"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "abbas.codigo@gmail.com"
EMAIL_HOST_PASSWORD = "mond zenp tfjj uoxy"

# Comma-separated extra admin addresses for booking notifications (optional).
BOOKING_ADMIN_EMAILS = [
    e.strip()
    for e in os.environ.get("BOOKING_ADMIN_EMAILS", "").split(",")
    if e.strip()
]

# True: client + admin booking mails use only EMAIL_HOST_USER / BOOKING_ADMIN_EMAILS (no consultant CC).
# Set env BOOKING_SINGLE_ADMIN_INBOX=false when multiple admins need consultant copies.
BOOKING_SINGLE_ADMIN_INBOX = os.environ.get("BOOKING_SINGLE_ADMIN_INBOX", "true").lower() in (
    "1",
    "true",
    "yes",
)

RECAPTCHA_PUBLIC_KEY = "6LfhyUUqAAAAALWtHDmDjfALmGvNkS__D9JH26Vz"
RECAPTCHA_PRIVATE_KEY = "6LfhyUUqAAAAAEUMGWOH46qR3OIbyCm79ugcJET4"




CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-codigomantra-cache",
    }
}

# So `website.zoom_meet` and other app loggers show Zoom/Google API warnings in the console
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "website": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# GOOGLE_AUTH_INFO = {
#     "token": os.getenv("G_TOKEN"),
#     "refresh_token": os.getenv("G_REFRESH_TOKEN"),
#     "client_id": os.getenv("G_CLIENT_ID"),
#     "client_secret": os.getenv("G_CLIENT_SECRET"),
#     "token_uri": os.getenv("G_TOKEN_URI", "https://googleapis.com"),
# }

# GOOGLE_AUTH_INFO = {
#     "token": config("G_TOKEN"),
#     "refresh_token": config("G_REFRESH_TOKEN"),
#     "client_id": config("G_CLIENT_ID"),
#     "client_secret": config("G_CLIENT_SECRET"),
#     "token_uri": config("G_TOKEN_URI", default="https://oauth2.googleapis.com/token"),
# }


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.dev",   # ✅ correct wildcard for your ngrok URL
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev",  # ✅ correct
]

# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'Custom',
#         'height': 400,
#         'width': 'auto',

#         'toolbar_Custom': [
#             ['Bold', 'Italic', 'Underline'],
#             ['NumberedList', 'BulletedList'],
#             ['TextColor', 'BGColor'],
#             ['Link', 'Unlink'],
#             ['Format'],
#             ['Undo', 'Redo'],
#             ['RemoveFormat'],
#             ['Source']
#         ],

#         'format_tags': 'p;h3;h4',
#         'line_height': '1;1.2;1.5;2;2.5;3',

#         'extraPlugins': ','.join([
#             'colorbutton',
#             'justify',
#             'liststyle',
#         ])
#     }
# }

KEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 400,
        'width': 'auto',

        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['TextColor', 'BGColor'],
            ['Link', 'Unlink'],
            ['Format'],
            ['Undo', 'Redo'],
            ['RemoveFormat'],
            ['Source']
        ],

        'format_tags': 'p;h3;h4',
        'line_height': '1;1.2;1.5;2;2.5;3',

        'extraPlugins': ','.join([
            'colorbutton',
            'justify',
            'liststyle',
        ]),

        # Inject spacing CSS 
        'contentsCss': [
            '/static/ckeditor/ckeditor/contents.css',  # keep default styles
            'data:text/css,' + (
                'body { font-size: 14px; line-height: 1.5; margin: 10px; }'

                # H1 — large section headings with big top spacing
                'h1 { font-size: 2em; margin-top: 60px; margin-bottom: 10px; font-weight: bold; }'
                'h1:first-child { margin-top: 0; }'

                # H3 — sub-section headings
                'h3 { font-size: 1.1em; margin-top: 20px; margin-bottom: 4px; font-weight: bold; }'

                # H4 — minor headings (bold labels like "Complex user experience:")
                'h4 { font-size: 1em; margin-top: 14px; margin-bottom: 2px; font-weight: bold; }'

                # Paragraphs — moderate spacing
                'p { margin-top: 0; margin-bottom: 10px; }'

                # Lists — tight, indented
                'ul, ol { margin-top: 4px; margin-bottom: 8px; padding-left: 24px; }'
                'li { margin-bottom: 3px; }'
            )
        ],
    }
}

